global using ApiDataLayer;
global using ApiDataLayer.Entities;
global using Microsoft.EntityFrameworkCore;
global using Api.Model;
global using Api.Extensions;
global using Microsoft.Identity.Web.Resource;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;