name: Api unittest

on:
  push:
    branches: 
        - Develop
        - Api
  pull_request:
    branches:
        - Develop

jobs:
  UnitTest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore SvendeProve.sln
    - name: Build
      run: dotnet build SvendeProve.sln --no-restore
    - name: Test
      run: dotnet test SvendeProve.sln --no-build --verbosity normal
